version: '3.8'

services:

  webnginx:
    image: nginx:stable-alpine
    container_name: webnginx
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/web.vhost:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8082:80"
    depends_on:
      - phpframework
    networks:
      - app-network
    restart: unless-stopped

  phpframework:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php83
    volumes:
      - .:/var/www/html:delegated
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  php-data: