version: '3.7'

services:

  webnginx:
    image: nginx:stable
    container_name: webnginx
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/web.vhost:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"

  phpframwork:
      build:
        context: docker/php
      container_name: php83
      volumes:
        - .:/var/www/html

